language: android

jdk: oraclejdk8
sudo: required
dist: trusty
compiler: gcc

android:
  components:
    - tools

before_script:
    - sleep 3; echo y | sdkmanager --update
    - (while sleep 3; do echo "y"; done) | sdkmanager "build-tools;26.0.1" "extras;android;m2repository" "ndk-bundle"
    - echo | sudo add-apt-repository ppa:jonathonf/python-3.6
    - sudo apt-get update
    - sudo apt-get install -y python3.6

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - PATH=/usr/local/android-sdk/ndk-bundle:${PATH}

script:
    - python3.6 ${TRAVIS_BUILD_DIR}/build.py all 13.6 1360
