language: android

jdk: oraclejdk8
sudo: required
dist: trusty
compiler: gcc

python:
    - "3.6"

android:
  components:
    - tools

after_install:
    - echo y | sdkmanager --update extras;google;m2repository
    - echo y | sdkmanager --update platform-tools
    - echo y | sdkmanager --update platforms;android-26
    - echo y | sdkmanager --update tools
    - echo y | sdkmanager build-tools;26.0.1
    - echo y | sdkmanager extras;android;m2repository
    - echo y | sdkmanager ndk-bundle

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - PATH=/usr/local/android-sdk/ndk-bundle:${PATH}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - ls -l
    - python3 ${TRAVIS_BUILD_DIR}/build.py all 13.6 1360
