language: android

jdk: oraclejdk8
sudo: required
dist: trusty
compiler: gcc

python:
    - "3.6"

android:
  components:
    - tools

before_script:
    - echo y | sdkmanager --update
    - echo y | sdkmanager "build-tools;26.0.1"
    - echo y | sdkmanager "extras;android;m2repository"
    - echo y | sdkmanager ndk-bundle
    - echo | sudo add-apt-repository ppa:jonathonf/python-3.6
    - sudo apt-get update
    - sudo apt-get install -y python3.6

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - PATH=/usr/local/android-sdk/ndk-bundle:${PATH}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - python3 --version
    - python3 ${TRAVIS_BUILD_DIR}/build.py all 13.6 1360
