language: android

jdk: oraclejdk8
sudo: required
dist: trusty
compiler: gcc

python:
    - "3.6"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - ndk-bundle

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk

script: python3 TheComputerGuy96/Magisk/build.py all 13.6 1360